# Generated by rust2rpm 27
%bcond check 1

# prevent library files from being installed
%global cargo_install_lib 0

Name:           cyan-skillfish-governor-smu
Version:        v0.4.6
Release:        1.20260619120402457887.update.deps.3.g14080b4%{?dist}
Summary:        # FIXME

SourceLicense:  MIT
# FIXME: paste output of %%cargo_license_summary here
License:        MIT
# LICENSE.dependencies contains a full license breakdown

URL:            https://github.com/filippor/cyan-skillfish-governor
Source:         cyan-skillfish-governor-smu-v0.4.6.tar.gz

BuildRequires: systemd cargo-rpm-macros >= 26 libdrm-devel

Requires(post): systemd
Requires(preun): systemd
Requires(postun): systemd


%global _description %{expand:
%{summary}.}

%description %{_description}

%prep
%autosetup -n cyan-skillfish-governor-smu-v0.4.6 -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
export CYAN_SKILLFISH_GOVERNOR_VERSION=%{version}
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
export CYAN_SKILLFISH_GOVERNOR_VERSION=%{version}
%cargo_install
mkdir -p %{buildroot}/%{_unitdir}
cp %name.service %{buildroot}/%{_unitdir}/%name.service
mkdir -p %{buildroot}%{_sysconfdir}/%name/
cp default-config.toml %{buildroot}%{_sysconfdir}/%name/config.toml
install -Dm755 scripts/cyan-skillfish-performance-mode %{buildroot}%{_bindir}/cyan-skillfish-performance-mode
mkdir -p %{buildroot}%{_datadir}/dbus-1/system.d/
cp com.cyanskillfish.Governor.conf %{buildroot}%{_datadir}/dbus-1/system.d/com.cyanskillfish.Governor.conf
mkdir -p %{buildroot}/usr/lib/systemd/system-preset/
#echo "enable %name.service" > %{buildroot}/usr/lib/systemd/system-preset/50-%name.preset

%post
%systemd_post %name.service
/bin/systemctl %name.service >/dev/null 2>&1 || :

%preun
%systemd_preun %name.service

%postun
%systemd_postun_with_restart %name.service

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE
%license LICENSE.dependencies
%doc README.md
%{_bindir}/%name
%{_bindir}/cyan-skillfish-performance-mode
%{_sysconfdir}/%name/config.toml
%{_unitdir}/%name.service
%{_datadir}/dbus-1/system.d/com.cyanskillfish.Governor.conf
#/usr/lib/systemd/system-preset/50-#name.preset


%changelog
%autochangelog
