# Generated by rust2rpm 27
%bcond check 1

# prevent library files from being installed
%global cargo_install_lib 0

Name:           cyan-skillfish-governor-tt
Version:        v0.1.3
Release:        1.20250824121733165179.package.fedora.1.g07d7fe2%{?dist}
Summary:        # FIXME

SourceLicense:  MIT
# FIXME: paste output of %%cargo_license_summary here
License:        MIT
# LICENSE.dependencies contains a full license breakdown

URL:            https://github.com/filippor/cyan-skillfish-governor
Source:         cyan-skillfish-governor-v0.1.3.tar.gz

BuildRequires:  cargo-rpm-macros >= 26 libdrm-devel

%global _description %{expand:
%{summary}.}

%description %{_description}

%prep
%autosetup -n cyan-skillfish-governor-v0.1.3 -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install
mkdir -p %{buildroot}/usr/lib/systemd/system/
cp cyan-skillfish-governor.service %{buildroot}/usr/lib/systemd/system/cyan-skillfish-governor.service
mkdir -p %{buildroot}%{_sysconfdir}/cyan-skillfish-governor/
cp default-config.toml %{buildroot}%{_sysconfdir}/cyan-skillfish-governor/config.toml


%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE
%license cyan-skillfish-governor-v0.1.2-build/cyan-skillfish-governor-v0.1.2/LICENSE
%license cyan-skillfish-governor-v0.1.3-build/cyan-skillfish-governor-v0.1.3/LICENSE
%license LICENSE.dependencies
%doc README.md
%{_bindir}/cyan-skillfish-governor
%{_sysconfdir}/cyan-skillfish-governor/config.toml
/usr/lib/systemd/system/cyan-skillfish-governor.service

%changelog
%autochangelog
