# Generated by rust2rpm 27
%bcond check 1

# prevent library files from being installed
%global cargo_install_lib 0

Name:           cyan-skillfish-governor-tt
Version:        0.1.3.1
Release:        1.20251207225329323879.tt.5.g1ff46b5%{?dist}
Summary:        # FIXME

SourceLicense:  MIT
# FIXME: paste output of %%cargo_license_summary here
License:        MIT
# LICENSE.dependencies contains a full license breakdown

URL:            https://github.com/filippor/cyan-skillfish-governor
Source:         cyan-skillfish-governor-tt-0.1.3.1.tar.gz

BuildRequires: systemd cargo-rpm-macros >= 26 libdrm-devel

Requires(post): systemd
Requires(preun): systemd
Requires(postun): systemd


%global _description %{expand:
%{summary}.}

%description %{_description}

%prep
%autosetup -n cyan-skillfish-governor-tt-0.1.3.1 -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install
mkdir -p %{buildroot}/%{_unitdir}
cp cyan-skillfish-governor.service %{buildroot}/%{_unitdir}/cyan-skillfish-governor.service
mkdir -p %{buildroot}%{_sysconfdir}/cyan-skillfish-governor/
cp default-config.toml %{buildroot}%{_sysconfdir}/cyan-skillfish-governor/config.toml


%post
%systemd_post cyan-skillfish-governor.service
/bin/systemctl cyan-skillfish-governor.service >/dev/null 2>&1 || :

%preun
%systemd_preun cyan-skillfish-governor.service

%postun
%systemd_postun_with_restart cyan-skillfish-governor.service

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE
%license cyan-skillfish-governor-v0.1.2-build/cyan-skillfish-governor-v0.1.2/LICENSE
%license cyan-skillfish-governor-v0.1.3-build/cyan-skillfish-governor-v0.1.3/LICENSE
%license LICENSE.dependencies
%doc README.md
%{_bindir}/cyan-skillfish-governor
%{_sysconfdir}/cyan-skillfish-governor/config.toml
%{_unitdir}/cyan-skillfish-governor.service


%changelog
%autochangelog
